version: '2.0'
services:
  rasa:
    image: abelkmathew/rasa-healthbot
    ports:
      - 5005:5005
    volumes:
      - ./Chatbot/:/app
    command: 
      - run 
      - --cors 
      - "*" 
      - --enable-api
    
  action-server:
    image: abelkmathew/rasa-sdk:2.8.4-v5
    volumes:
      - ./Chatbot/actions/:/app/actions
    ports:
      - 5055:5055

  react-app:
    image: abelkmathew/react-bot-image:3.0
    volumes:
      - ./Website/src:/app/src
    ports:
      - 3000:3000
    user: root
