version: '3.0'
services:
  rasa:
    image: abelkmathew/rasa-healthbot
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: 
      - run
    
  action-server:
    image: rasa/rasa-sdk:2.8.4
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055